# Generated by Django 3.2.6 on 2021-09-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(choices=[('Zoom', 'Zoom'), ('GoogleMeet', 'GoogleMeet'), ('Youtube', 'Youtube'), ('Discord', 'Discord'), ('Teams', 'Teams'), ('Other', 'Other')], max_length=150),
        ),
    ]
