# Generated by Django 3.2.5 on 2021-08-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.CharField(choices=[('Zoom', 'Zoom'), ('GoogleMeet', 'GoogleMeet'), ('Teams', 'Teams'), ('Other', 'Other')], default=' ', max_length=150),
            preserve_default=False,
        ),
    ]
