# Generated by Django 3.2.5 on 2021-08-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210812_1818'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregister',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eventregister',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventregister',
            name='user',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventRegister',
        ),
    ]
