# Generated by Django 3.2.5 on 2021-08-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aproved',
            field=models.BooleanField(default=False),
        ),
    ]
