# Generated by Django 3.2.6 on 2021-08-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_auto_20210813_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, default='thasa', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Founder', 'Founder'), ('Co-Founder', 'Co-Founder'), ('Staff', 'Staff'), ('Teacher', 'Teacher'), ('Moderator', 'Moderator'), ('Member', 'Member')], default='Member', max_length=13),
        ),
    ]
