# Generated by Django 3.2.6 on 2021-09-09 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-points',)},
        ),
    ]
