# Generated by Django 3.2.5 on 2021-08-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Founder', 'Founder'), ('Co-Founder', 'Co-Founder'), ('Staff', 'Staff'), ('Moderator', 'Moderator'), ('Member', 'Member')], default=' ', max_length=13),
            preserve_default=False,
        ),
    ]
